version: '3.3'

volumes:
  jenkins-data:
  apache-data:
  cert-data:

secrets:
  jenkins.pass:
    file: ./jenkins.pass

services:

  jenkins:
    build: ./jenkins
    image: "rhub/cran-jenkins:0.0.2"
    volumes:
    - "jenkins-data:/var/jenkins_home"
    - "apache-data:/var/apache-data"
    - "/cran:/cran"
    environment:
    - JENKINS_ROOT_URL=https://cran2.r-pkg.org
    - JENKINS_USER=admin
    secrets:
    - jenkins.pass
    ports:
    - "8080:8080"
    - "4402:4402"
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        window: 60s

  jenkins-seed:
    build: ./seed
    image: "rhub/cran-jenkins-seed:0.0.2"
    depends_on:
    - jenkins
    environment:
    - JENKINS_USER=admin
    secrets:
    - jenkins.pass
    entrypoint:
    - bash
    - -c
    - /seed/jenkins.sh
    deploy:
      restart_policy:
        condition: on-failure

  apache:
    build: ./apache
    image: "rhub/cran-apache:0.0.2"
    volumes:
    - "/cran:/cran"
    - "apache-data:/usr/local/apache2/conf"
    - "cert-data:/etc/letsencrypt"
    entrypoint:
    - sh
    - -c
    - /entrypoint.sh
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        window: 60s
    environment:
    - LETSENCRYPT_EMAIL=csardi.gabor@gmail.com
    - CRAN_SERVER_NAME=cran2.r-pkg.org
    ports:
    - "80:80"
    - "443:443"
